"""Added created_at timestamp to Registration

Revision ID: 10218d0b065e
Revises: 5d286eb4b242
Create Date: 2025-01-31 08:32:38.051683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10218d0b065e'
down_revision = '5d286eb4b242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
